[phases.setup]
nixPkgs = ["python311Full", "nodejs"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "cd backend && python3 app.py"
